version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
before_build:
  - nuget restore src\HabitRPG.sln
build:
  project: src\HabitRPG.sln
  verbosity: minimal
artifacts:
  - path: bin
    name: HabitRPGHabitRPG
    type: zip
